package id.co.xinix.auth.exception;

public record ErrorDetail(Integer code, String message) {
}
